# Generated by Django 5.0.3 on 2024-07-06 14:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0002_alter_mail_date_alter_usersubcribes_subcribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 6, 14, 15, 46, 643908)),
        ),
        migrations.AlterField(
            model_name='usersubcribes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news_portal.category'),
        ),
    ]
