# Generated by Django 5.0.3 on 2024-07-06 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0003_alter_mail_date_alter_usersubcribes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 6, 14, 15, 48, 406444)),
        ),
    ]
